all:
  # Doc
  # https://github.com/kubernetes-sigs/kubespray/blob/master/docs/vars.md
  hosts:
    master01:
      ansible_host: 192.168.120.12
      ip: 192.168.120.12
      access_ip: 192.168.120.12
      etcd_member_name: etcd01
    worker01:
      ansible_host: 192.168.120.13
      ip: 192.168.120.13
      access_ip: 192.168.120.13
    worker02:
      ansible_host: 192.168.120.14
      ip: 192.168.120.14
      access_ip: 192.168.120.14
  children:
    kube-master:
      hosts:
        master01:
    kube-node:
      hosts:
        worker01:
        worker02:
    etcd:
      hosts:
        master01:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
