# cf. https://imranh.co.uk/2020/05/21/kubespray-ingress-loadbalancer.html
# cf. https://stackoverflow.com/questions/64000338/configure-metallb-with-kubernetes-running-on-different-vps-servers
---
# Source: ingress-nginx/templates/controller-service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/component: controller
  name: ingress-nginx-controller
  namespace: ingress-nginx
  annotations:
    # cf. https://github.com/kubernetes-sigs/kubespray/blob/2f2ed116f76f656dbb0a871b9b7e4dc1708718c4/roles/kubernetes-apps/metallb/templates/metallb-config.yml.j2#L18
    metallb.universe.tf/address-pool: loadbalanced
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.21.50
  externalTrafficPolicy: Cluster
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
